title: Brain Game
hero_image: images/banner.png
description: Program a timed quiz on times tables
original_url:
theme: cc-prototype
duration: 2
listed: false
ingredient: false
copyedit: false
interests:
technologies: "scratch"
steps:
  - title: Introduction